### ISSUE TITLE
Project Titles

### ISSUE THREAD

**Issue by ErSKS** [KCE/C#7]
- [x] Student Mgmt. System, 
- [ ] Employee Mgmt. System, 
- [x] Library System, 
- [ ] eAttendance Mgmt. System, 
- [x] Pharmacy Mgmt. System, 
- [ ] Blood Bank Mgmt. System, 
- [x] Kitchen Recipe
- [x] Workers’ Time Logger
- [ ] Hospital Mgmt. System, 
- [x] Hotel Reservation System, 
- [ ] Inventory Mgmt. System, 
- [ ] Canteen Billing System, 
- [x] Task Reminder 
- [ ] Number Plate Registration System, 
- [ ] Tax Payment System, 
- [x] eWallet, 
- [x] Mini-Mart Billing System, 
- [x] Tourist Entry Logger, 
- [ ] Feedback Mgmt. System, 
- [ ] Project Info. System,
- [x] Khwopa Quiz
- [x] Class Routine Mgmt. System
- [x] Bank Mgmt. System
- [ ] Student Payroll System
- [x] Break-Game
- [x] Land Converter
- [ ] Prescription Logger
- [x] Tic-tac-toe
- [x] Bag Chal
- [ ] Hostel Mgmt. System
- [x] Date Converter
- [x] Marksheet Generator
- [x] Hangman
- [x] Scientific Calculator
- [x] Telephone Directory
- [x] eVoting
- [ ] Puzzle
- [x] Data Encryption/Decryption
- [ ] Data Compression

**Comment by ashish-l0gme** [comment]
Team Name : PA³

Project Name : CashMan

Project on : e-wallet

Group Members
1) Ashish Kr. Sah
2) Arjun Baral
3) Anish Mainali
4) Poshan Bhandari

Team Leader : Ashish Kr. Sah

Faculty : B.E (Electrical)

**Comment by ErSKS** [comment]
# Projects Selected by BEL 2075 Batch

1. Student Mgmt. System, 
2. Library System, 
3. Kitchen Recipe
4. eWallet, 
5. Khwopa Quiz,
6. Class Routine Mgmt. System,
7. Break-Game,
8. Date Converter,
9. Marksheet Generator,
10. Hangman,
11. Scientific Calculator &
12. Data Encryption/Decryption

**Comment by ErSKS** [comment]
# Projects Selected by BCT 2075 Batch

1. Pharmacy Mgmt. System, 
2. Workers’ Time Logger
3. Hospital Mgmt. System, 
4. Hotel Reservation System, 
5. Task Reminder 
6. Mini-Mart Billing System, 
7. Tourist Entry Logger, 
8. Bank Mgmt. System
9. Land Converter
10. Tic-tac-toe
11. Telephone Directory
12. eVoting
