### ISSUE TITLE
Submit your Project Information

### ISSUE THREAD

**Issue by ErSKS** [KCE/C#8]
- Team Name
- Project Name
- Project Member
- Team Leader
- Faculty

**Comment by rikit1** [comment]
1. Mission Marksheet
2.Marksheet Generator(MSG)
3.Rakesh Yadav
Shanti Karki
Devraj Neupane 
Rikit Parajuli
4.Rikit Parajuli
5.B.E Electrical

**Comment by NibanK** [comment]
Team Name: Creators
Project Name: Bag Chal
Project Member: 1>Nabin Kawan
                               2>Ronish Shrestha
                               3>Rubin Baidhya
                               4>Sudeep Kasichwaa
Team Leader: Nabin Kawan
Faculity: Computer Science

**Comment by rikit1** [comment]
Team Name  :Marksheet Builders
Project Name : Marksheet Generator
Project members: Rakesh yadav
                             Rikit parajuli
                             Shanti Karki
                             Devraj neupane
Team leader :Rikit Parajuli
Faculty:  Electrical

**Comment by prashant5126** [comment]
Team name: wasa pasa
Project name:Pharmacy management system
Project members:prashant manandhar
Pratik Shakya
Anish machamachi
Roman silpakar
Team leader:prashant manandhar
Faculty :computer

**Comment by shresthasanish24** [comment]
Team Name :: Europa
Project name :: Worker's time Logger
Project Members ::
     1) Sanish Shrestha
     2) Sudip Shrestha
     3) Anup Kafle
     4) Rochak Sedai
Team Leader :: Sanish Shrestha
Faculty :: Computer

**Comment by Anuragkafle** [comment]
TEAM NAME              : Q-KRAB
PROJECT NAME        : HANGMAN
PROJECT MEMBERS: 1)ANURAG KAFLE
                                        2)BIPIN SHRESTHA
                                        3)KUSHAL POUDEL
                                        4)ROHIT SHARMA
TEAM LEADER           : ANURAG KAFLE
FACULTY                     : ELECTRICAL

**Comment by sakar5157** [comment]
Team Name: The Creators !!!
Project Name: e-Voting  
Project Members: 
1: Sakar Paudel (LEADER)
2: Nitesh Kumar Daas
3: Anushil Timsina
4: Sandeep Subedi

Faculity: Computer Engineering ( BCT )

**Comment by dipesjoshi** [comment]
Team name :  Squad
Project name:Hotel Reservation
Project members: 
1) Dipesh Joshi
2) Bibek Manadhar
3) Pratirodh Pokharel
4) Sudip Manandhar
            
Project leader: Dipesh Joshi
Faculty:  Computer

**Comment by Shreeshuva** [comment]
Team name: Quizers!!!
Project name: Khwopa Quiz
Project members: 
1: Shreeshuva Maharjan
2: Bijay Tamang
3: Suman Syangtan
4: Sujan Sharma

Team leader: Shreeshuva Maharjan
Faculty: Electrical

**Comment by rravii** [comment]
Team Name: Frolo Canton
Project Name: Tic-tac-toe
Project Members:
1) Aabhas Dhaubanja
2) Samriddha Shrestha
3) Amit Duwal
4) Ravi Pandit
Team Leader: Ravi Pandit
Faculty: Computer

**Comment by Aaryashree** [comment]
Team Name: Clovers
Project Name:Telephone directory 
Project Member: -Nikita Pokharel
                           -Aaryashree Pokharel
                           -Rakshya Belbase 
                           -Shyamron Dangol
Team Leader -Aaryashree Pokharel
Faculty-Computer

**Comment by Abhinav0008** [comment]
Team Name : Kops
Project Name : Break Games
Project Member :
   1) Abhinav Parajuli
   2) Parashar Khanal
   3) Roshan Shahi
   4) Bijay Pokharel
Team Leader : Abhinav Parajuli
 Faculty : Electrical

**Comment by Abhinav0008** [comment]
Team Name : Kops
Project Name : Break Games
Project Member :
1) Abhinav Parajuli
2) Parashar Khanal
3) Roshan Shahi
4) Bijay Pokharel
Team Leader : Abhinav Parajuli
Faculty : Electrical

**Comment by Abhinav0008** [comment]
Team Name : Kops
Project Name : Break Games
Project Member :
   1) Abhinav Parajuli
   2) Parashar Khanal
   3) Roshan Shahi
   4) Bijay Pokharel
Team Leader : Abhinav Parajuli
Faculty : Electrical

**Comment by Abhinav0008** [comment]
Team Name : Kops
Project Name : Break Games
Project Member :
1. Abhinav Parajuli
2. Parashar Khanal
3. Roshan Shahi
4. Bijay Pokharel
Team Leader : Abhinav Parajuli
Faculty : Electrical

**Comment by Abhinav0008** [comment]
Team Name : Kops
Project Name : Break Games
Project Member : 
  1. Abhinav Parajuli
  2. Parashar Khanal
  3. Roshan Shahi
  4. Bijay Pokharel

Team Leader : Abhinav Parajuli
Faculty : Electrical

**Comment by pratigya1** [comment]
Team Name: (PS)^2
Project name : Kitchen Recipe 
Project Member : 
1. Pratigya Shrestha 
2. Purnima GM 
3. Sarika Shrestha 
4. Sunita Budhathoku 

Team Leader :Pratigya Shrestha 
Faculty : Electrical

**Comment by StructHack** [comment]
- **Team Name**  : **0xByte**
- **Project Name** : **Data Encryption/Decryption**
- **Project Members**:
    _1. Dipendra Shrestha
    2. Rabin Sapkota
    3. Dipesh Upadhayaya
    4. Binod Aryal_
- **Team Leader** : **Dipendra Shrestha**
- **Faculty** : **Electrical**

**Comment by niteshthapa33** [comment]
TEAM NAME: KISUN
PROJECT NAME : DATE CONVETER
TEAM MEMBER : KIRAN DARNAL ,SURAJ SHRESTHA ,NITESH THAPA
TEAM LAEDER: NITESH THAPA
FACULTY:ELECTRICAL

**Comment by Anshu18Bhattarai** [comment]
Team name : ADAR
Project name : Class-Routine Management System
Team members : Anshu Bhattarai
                              Dhiraj Shrestha
                              Anjan Shrestha
                              Ranjan Raj Pandey
Team leader : Anshu Bhattarai
Faculty : Electrical

**Comment by SaminSH7** [comment]
Team Name : CASIO
Project Name : Scientific Calculator
Team Leader : Samin Hona
Project Members : 
1. Samin Hona
2. Udayamani Neupane
3. Swornim K.C.
4. Aaditya Raj Thakur

**Comment by Riya5656** [comment]
Team name: Aerial
Project name: Tourist Entry Logger
Project members:
1: Anu Maharjan
2: Laxmi Shrestha
3: Riya Parajuli
4: Isha Valandyo

Team leader: Riya Parajuli
Faculty: Computer

**Comment by iTwanaz** [comment]
Team name : Team Bankers
Project Name : Bank Managemenrt System
Project Members:
1) Aayush Twayana(Leader)
2) Anish Shilpakar
3) Anjan Khadka
4) Bimal Bhoyadyo

Faculty : Computer

**Comment by Nehagupta121** [comment]
Team name:Dynamite 
Project name:student management system
Project members:
           1.Niruta Gyawali
           2.Neha Gupta
           3.Parbati Basnet
           4.Ashika Dhital
            Team leader :Neha Gupta
            Faculty :Electrical

**Comment by Poshanb** [comment]
Team Name : PA³

Project Name : CashMan

Project on : e-wallet

Group Members

Ashish Kr. Sah
Arjun Baral
Anish Mainali
Poshan Bhandari
Team Leader : Ashish Kr. Sah

Faculty : B.E. (Electrical)
